#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-only

set -e

TARGET="${1:?usage: customize03-shairport.sh <rootfs dir>}"
CONF="$TARGET/etc/shairport-sync.conf"

mkdir -p "$TARGET/etc"

if [ ! -f "$CONF" ]; then
    cat > "$CONF" <<'EOF'
// /etc/shairport-sync.conf - ZYBO Audio release configuration (generated by
// hooks/customize03-shairport.sh in zybo-debian; do not edit by hand, change
// the hook and rebuild the image). See the shairport-sync sample or `man shairport-sync`.

general =
{
	// Clock-drift correction must use a real resampler. shairport continuously
	// resamples to track the sender's clock (~965 ppm on this board); with "basic"
	// (linear interpolation) that is AUDIBLE as continuous ticking. soxr costs
	// ~22.35 ms per resample (just under shairport's own 30 ms threshold) and one
	// thread spins at ~105% CPU -- accepted, it is the only setting that is clean.
	interpolation = "soxr";
	// WiFi jitter drains the 0.2 s default. 0.4 s was tried to shorten the
	// play/pause delay, but it underran 10 times in 33 minutes on the board and
	// every recovery drops 0.07-0.13 s of audio (an audible pause or click).
	audio_backend_buffer_desired_length_in_seconds = 1.0;
	// The board has exactly one volume knob: the WebUI writes the codec's ALSA
	// "Master" control and every source plays at unity into it. If shairport applies
	// the sender's volume in software instead, the phone's -20 dB lands on
	// shairport's own -96 dB scale (~-64 dB) and AirPlay becomes inaudible next to
	// the other sources -- so ignore the sender's volume.
	ignore_volume_control = "yes";
	// Never use that control's +5 dB top end: the codec Master maps raw 48..127 to
	// -74..+5 dB, so anything above 0 dB is digital gain, i.e. clipping.
	volume_max_db = 0.0;
	// Its *native* dB range is not usable either: ALSA cannot map raw 0..47 at all
	// (it reports -99999.99 dB) and a value written there is silence. Pin the range
	// instead of letting shairport derive it from the mixer.
	volume_range_db = 60;
};

diagnostics =
{
	// Release configuration: all diagnostics off (only enabled while debugging)
	log_verbosity = 0;
	statistics = "no";
};
EOF
    echo "[hook] shairport-sync config missing -> created $CONF"
else

awk '
BEGIN {
    SUBSEP = "\034"
    depth = 0; sec = ""; pend = ""

    nsec = 2; slist[1] = "general"; slist[2] = "diagnostics"

    nw["general"] = 5
    wkey["general", 1] = "interpolation"
    wval["general", 1] = "\tinterpolation = \"soxr\"; // the drift correction must be a real resampler: \"basic\" (linear interpolation) is audible as continuous ticking"
    wkey["general", 2] = "audio_backend_buffer_desired_length_in_seconds"
    wval["general", 2] = "\taudio_backend_buffer_desired_length_in_seconds = 1.0; // 0.4 underran 10 times in 33 min under WiFi jitter, and each recovery drops 0.07-0.13 s of audio (audible pause/click); 1.0 keeps enough slack"
    wkey["general", 3] = "ignore_volume_control"
    wval["general", 3] = "\tignore_volume_control = \"yes\"; // one volume knob, on the board: a sender volume would land on the -96 dB software scale of shairport (~-64 dB) and make AirPlay inaudible"
    wkey["general", 4] = "volume_max_db"
    wval["general", 4] = "\tvolume_max_db = 0.0; // one system volume: never use the +5 dB top end of the codec Master control (that is digital gain, i.e. clipping)"
    wkey["general", 5] = "volume_range_db"
    wval["general", 5] = "\tvolume_range_db = 60; // pin the range: the native dB range of the mixer is unusable (ALSA cannot map raw 0..47, so a session volume could land in silence)"

    nw["diagnostics"] = 2
    wkey["diagnostics", 1] = "log_verbosity"
    wval["diagnostics", 1] = "\tlog_verbosity = 0; // release configuration: not the 3 used while debugging"
    wkey["diagnostics", 2] = "statistics"
    wval["diagnostics", 2] = "\tstatistics = \"no\"; // release configuration: not the yes used while debugging"
}

# Section header on its own line: name =
depth == 0 && $0 ~ /^[ \t]*[A-Za-z_][A-Za-z0-9_]*[ \t]*=[ \t]*$/ {
    pend = $0; sub(/[ \t]*=[ \t]*$/, "", pend); sub(/^[ \t]*/, "", pend)
    print; next
}

# Section header and opening brace on one line: name = {
$0 ~ /^[ \t]*[A-Za-z_][A-Za-z0-9_]*[ \t]*=[ \t]*\{[ \t]*$/ {
    s = $0; sub(/[ \t]*=.*/, "", s); sub(/^[ \t]*/, "", s)
    print; sec = s; depth = 1; seen[s] = 1; next
}

# Opening brace (following a section header on the previous line)
depth == 0 && $0 ~ /^[ \t]*\{[ \t]*$/ {
    print; sec = pend; depth = 1; seen[sec] = 1; next
}

# End of section: append any missing mandatory keys for that section
depth == 1 && $0 ~ /^[ \t]*\}[ \t]*;?[ \t]*$/ {
    for (i = 1; i <= nw[sec]; i++) {
        k = sec SUBSEP wkey[sec, i]
        if (!(k in found)) { print wval[sec, i]; found[k] = 1 }
    }
    print; sec = ""; depth = 0; next
}

{
    if (depth == 1 && sec != "") {
        t = $0
        sub(/^[ \t]+/, "", t)
        active = 1
        if (t ~ /^\/\//) { active = 0; sub(/^\/\/[ \t]*/, "", t) }
        key = t
        sub(/[ \t]*=.*/, "", key)
        if (key ~ /^[A-Za-z_][A-Za-z0-9_]*$/) {
            for (i = 1; i <= nw[sec]; i++) {
                if (key == wkey[sec, i]) {
                    k = sec SUBSEP key
                    if (!(k in found)) { print wval[sec, i]; found[k] = 1 }
                    next
                }
            }
            # log_output_to = "stderr" used while debugging must not stay in a release config (the default is syslog)
            if (sec == "diagnostics" && key == "log_output_to" && active) {
                print "//\tlog_output_to = \"syslog\"; // release configuration: use the default; only set \"stderr\" while debugging"
                next
            }
        }
    }
    print
}

# The file has no general / diagnostics section at all -> append them at the end
END {
    for (j = 1; j <= nsec; j++) {
        s = slist[j]
        if (!(s in seen)) {
            print ""
            print s " ="
            print "{"
            for (i = 1; i <= nw[s]; i++) print wval[s, i]
            print "};"
        }
    }
}
' "$CONF" > "$CONF.zybo-new"
    mv -f "$CONF.zybo-new" "$CONF"
fi

sed -i 's|^[[:space:]]*mixer_control_name[[:space:]]*=.*|// mixer_control_name removed by customize03: the board keeps its own volume (see customize04-volume.sh)|' "$CONF"

fail() { echo "[hook] ERROR: shairport-sync config validation failed: $1" >&2; exit 1; }

grep -qE '^[[:space:]]*interpolation[[:space:]]*=[[:space:]]*"soxr"[[:space:]]*;' "$CONF" \
    || fail 'interpolation is not "soxr" (with "basic" the linear-interpolation drift correction is audible as ticking)'
grep -qE '^[[:space:]]*audio_backend_buffer_desired_length_in_seconds[[:space:]]*=[[:space:]]*1\.0[[:space:]]*;' "$CONF" \
    || fail 'audio_backend_buffer_desired_length_in_seconds is not 1.0'
grep -qE '^[[:space:]]*ignore_volume_control[[:space:]]*=[[:space:]]*"yes"[[:space:]]*;' "$CONF" \
    || fail 'ignore_volume_control is not "yes" (the sender volume would make AirPlay ~64 dB quieter than every other source)'
grep -qE '^[[:space:]]*log_verbosity[[:space:]]*=[[:space:]]*0[[:space:]]*;' "$CONF" \
    || fail 'diagnostics.log_verbosity is not 0'
grep -qE '^[[:space:]]*statistics[[:space:]]*=[[:space:]]*"no"[[:space:]]*;' "$CONF" \
    || fail 'diagnostics.statistics is not "no"'
grep -qE '^[[:space:]]*log_verbosity[[:space:]]*=[[:space:]]*3' "$CONF" \
    && fail 'debugging value log_verbosity = 3 is still present'

grep -qE '^[[:space:]]*mixer_control_name[[:space:]]*=' "$CONF" \
    && fail 'mixer_control_name is set: the sender would overwrite the board volume and re-write it on every poll'
grep -qE '^[[:space:]]*volume_max_db[[:space:]]*=[[:space:]]*0(\.0)?[[:space:]]*;' "$CONF" \
    || fail 'general.volume_max_db is not 0.0 (the codec Master control reaches +5 dB, which would clip)'
grep -qE '^[[:space:]]*volume_range_db[[:space:]]*=[[:space:]]*60[[:space:]]*;' "$CONF" \
    || fail 'general.volume_range_db is not 60 (the mixer native dB range is unusable: raw 0..47 has no dB mapping)'

for k in interpolation audio_backend_buffer_desired_length_in_seconds ignore_volume_control \
         log_verbosity statistics volume_max_db volume_range_db; do
    n="$(grep -cE "^[[:space:]]*${k}[[:space:]]*=" "$CONF" || true)"
    [ "$n" -eq 1 ] || fail "key $k appears $n times (must be exactly 1; duplicate keys make shairport-sync refuse to start)"
done

echo "[hook] shairport-sync configuration applied"
grep -nE '^[[:space:]]*(interpolation|audio_backend_buffer_desired_length_in_seconds|ignore_volume_control|log_verbosity|statistics|volume_max_db|volume_range_db)[[:space:]]*=' "$CONF" | sed 's/^/  /'
n_mixer="$(grep -cE '^[[:space:]]*mixer_control_name[[:space:]]*=' "$CONF" || true)"
echo "[hook] shairport-sync does not own the codec mixer (active mixer_control_name lines: $n_mixer)"
